# Generated by Django 4.2.6 on 2023-10-11 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('care_instructions', models.TextField()),
                ('blooming_season', models.CharField(max_length=255)),
                ('origin', models.CharField(blank=True, max_length=255, null=True)),
                ('warning_signs', models.TextField(blank=True, null=True)),
                ('health_indicators', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='flowers/')),
                ('likes', models.ManyToManyField(blank=True, to='users.user')),
            ],
        ),
    ]
